cypress/fixtures/rosa-hosted/RosaClusterHostedWizardValidation.json
cypress/fixtures/rosa/RosaClusterClassicWizardValidation.json

OCMUI e2e tests - fixed ROSA wizard validation test failures
Fixes [OCMUI-3652](https://issues.redhat.com/browse/OCMUI-3652)
Recent QE CI [runs](https://ci.int.devshift.net/job/RedHatInsights-uhc-portal-qe-gh-cypress-smoke/187/display/redirect) reported failures related to ROSA wizard validation e2e tests.
This is because of change in the product feature definition as part of OCMUI-3569 
Run the test
`npx cypress run --browser chrome --config baseUrl='https://console.dev.redhat.com/openshift/' --spec cypress/e2e/rosa/RosaClusterClassicWizardValidation.js`  
nil

[OCMUI-3652]e2e tests - fixed ROSA wizard validation test failures

---

cypress/e2e/rosa-hosted/RosaHostedClusterOverviewActions.js
cypress/pageobjects/ClusterDetails.page.js

E2e tests - fixed failing rosa hosted overview actions (day2) test case.
Fixes [OCMUI-3658](https://issues.redhat.com/browse/OCMUI-3658) 
Recent feature updates on product definition including PF6 updates were caused failures rosa hosted overview actions (day2) test cases. This PR provide necessary steps to fix the failing test cases.
- Create a rosa-hosted cluster with the name `cyp-rosa-hosted-public`
-  Run the below test case
- `yarn cypress-headless  --browser chrome --config baseUrl='https://prod.foo.redhat.com:1337/openshift/' --spec cypress/e2e/rosa-hosted/RosaHostedClusterOverviewActions.js`
nil

[OCMUI-3658]e2e tests - fixed failing rosa hosted overview actions test case.

---

src/components/clusters/ClusterDetailsMultiRegion/components/ClusterDetailsTop/ClusterDetailsTop.jsx
src/components/clusters/ClusterDetailsMultiRegion/components/ClusterDetailsTop/ClusterDetailsTop.test.jsx
src/components/clusters/ClusterDetailsMultiRegion/components/ClusterDetailsTop/components/ClusterStatusMonitor/ClusterStatusMonitor.jsx
src/components/clusters/wizards/rosa/CreateRosaGetStarted/CreateRosaGetStarted.tsx
src/components/clusters/wizards/rosa/common/Banners/RosaArchitectureRenamingAlert.tsx

This PR addresses the followup requests, coming from PMs, to add the ROSA Architecture Renaming Alert Banner to the Cluster Details page of ROSA clusters.
It also switches between the description and the Banner on the ROSA Get Started page as requested to group the alerts together. 
More details can be found on the Epic linked to the story this PR comes to address. 
This PR also addresses some white space changes necessary for those changes, which are debatable and optional, but I thought I should correct them in the same effort.
There was also a tiny spelling issue in one of the test names I corrected.
Link to issue: [OCMUI-3671](https://issues.redhat.com/browse/OCMUI-3671)
Go to Cluster Details page of a ROSA Classic & HCP Clusters
Verify that the new Alert Banner is present for both …

[OCMUI-3671] ROSA Architecture Rename Followup

---

docs/unit-testing.md
jest.config.js
src/components/clusters/common/TransferClusterOwnershipDialog/utils/__tests__/transferClusterOwnershipDialogSelectors.test.ts

To prevent mocking bleed-over from one test to another,  this PR changes the jest config so mocks are cleared before each test.  See: https://jestjs.io/docs/configuration#clearmocks-boolean
Note: No application code has changed
Fixes [OCMUI-3675](https://issues.redhat.com/browse/OCMUI-3675) 
This PR also fixes tests that were broken with config change.
Run `yarn test` :-) 

OCMUI-3675 Clear mocks before every unit test

---

src/components/clusters/ClusterDetailsMultiRegion/components/ClusterLogs/LogTable.tsx
src/components/clusters/ClusterDetailsMultiRegion/components/MachinePools/MachinePoolsTable.jsx

This PR adds screen-reader text for table headers that currently do not have text.  After this PR the following error will not be displayed the unit test output:  `table headers must have an accessible name`
Fixes [OCMUI-3588](https://issues.redhat.com/browse/OCMUI-3588)
Fixes [OCMUI-3589](https://issues.redhat.com/browse/OCMUI-3589)
Changes were only made to the headers without text.  Other table logic/layout have not been changed.
NOTE: This was copied from #8 
Go to a ROSA or OSD cluster
On the "Cluster history" tab, ensure that the table looks correctly - especially the table headers
On the "Machine pools" tab,  ensure that the table looks correctly - especially the table headers
Run the tests and have the output into a file.  For example `yarn run test > test-results.txt`
In the test …

OCMUI-3588, OCMUI-3589 - Add accessibility table header

---

src/components/clusters/wizards/common/ReviewCluster/AwsVpcTable.tsx
src/components/clusters/wizards/rosa/ReviewClusterScreen/ReviewClusterScreen.scss

On the HCP wizard confirmation page on medium to smaller screens, the machine pool subnets overlap on Safari.
Note that this was an issue only on Safari and not seen in other browsers.  There was no code changes and for most users there is an extremely minimal change.
Fixes [OCMUI-3619](https://issues.redhat.com/browse/OCMUI-3619) 
This appears to be a weird quirk on Safari with our code base - I couldn't reproduce with a native PF grid.  The review page is complicated with numerous nested items that normally  aren't nested (a grid inside of a list item for example).  While I can't rule out a PF bug - it is most likely due to our nesting of items.
The the "correct" fix would be to completely re-architect and re-design the confirmation page, that seemed a little heavy-handed so a single …

OCMUI-3619 On HCP wizard confirm, fix overlapping subnets

---

src/common/modals/ConfirmationDialog.tsx
src/components/SyncEditor/SyncEditorModal.tsx
src/components/clusters/ClusterDetailsMultiRegion/components/AccessControl/ExternalAuthentication/BreakGlassCredentialDetailsModal.tsx
src/components/clusters/ClusterDetailsMultiRegion/components/AccessControl/ExternalAuthentication/DeleteExternalAuthProviderModal.tsx
src/components/clusters/ClusterDetailsMultiRegion/components/AccessControl/ExternalAuthentication/ExternalAuthProviderModal.tsx
src/components/clusters/ClusterDetailsMultiRegion/components/AccessControl/ExternalAuthentication/RevokeBreakGlassCredentialsModal.tsx
src/components/clusters/ClusterDetailsMultiRegion/components/ClusterLogs/toolbar/ClusterLogsDownload.tsx
src/components/clusters/ClusterDetailsMultiRegion/components/Networking/components/EditApplicationIngressDialog/EditApplicationIngressDialog.tsx
src/components/clusters/ClusterDetailsMultiRegion/components/Overview/BillingAccount/OverviewBillingAccountModal.tsx
src/components/clusters/ClusterDetailsMultiRegion/components/UpgradeSettings/UpgradeSettingsTab.tsx
src/components/clusters/ClusterTransfer/AcceptDeclineTransferModal.tsx
src/components/clusters/ClusterTransfer/CancelClusterTransferModal.tsx
src/components/clusters/common/InstallProgress/ActionRequiredModal.jsx
src/components/clusters/common/MachineConfiguration/components/MachineConfigurationModal.tsx
src/components/clusters/common/Upgrades/UpgradeAcknowledge/UpgradeAcknowledgeModal/UpgradeAcknowledgeModal.tsx

Update for the deprecated PF5 modals to align with the modern modular approach of PF6 Modal.
Assisted by: Cursor/GPT-5
[OCMUI-3603](https://issues.redhat.com/browse/OCMUI-3603)
There were 19 deprecated components. 2 Tile components, Wizard component and 16 modals.
This PR addresses 15 out of 16 Modal components. 16th modal is the wrapper that we utilize around ALL modals in the application. To address this particular component discussion is required, as it will be a much larger effort to update all the custom modals that we utilize.
I divided PR into 15 commits.
1 commit for each modal.
Please, look at the commit -> It should have the file name in the title.
Locate in the UI the modal mentioned in the commit and simply confirm that it looks and works as expected.
No visual changes …

OCMUI-3603: deprecated modals update

---

src/components/clusters/ClusterDetailsMultiRegion/components/ClusterDetailsTop/components/ClusterStatusMonitor/ClusterStatusMonitor.jsx

When installation fails, and there was an inflight checks error two alerts did not have margin between them. The PR simply adds a PF6 utility class that was missing on one of the alerts.
[OCMUI-3614](https://issues.redhat.com/browse/OCMUI-3614)
1. The easiest way to test is to use an existing cluster with ?env=production flag. Cluster name is kim-rosa-multi. It has both alerts present.
2. Confirm that all alerts present on ClusterDetails page have gaps between them.
| <img width="2716" height="1208" alt="image" src="https://github.com/user-attachments/assets/a5d56f40-ae3a-49db-b9d2-34eb16c6dc0f" …

OCMUI-3614: added spacing between alerts

---

.tekton/uhc-portal-pull-request.yaml

add unit-test coverage in konflux' 'pull-request' pipelines.
addresses [OCMUI-3696](https://issues.redhat.com/browse/OCMUI-3696)
considering the current status of test-coverage across the different CI systems:
|  | pull-requests | pushes to 'main' |
| --- | --- | --- |
| jenkins | ✅ |  |
| GH action | ✅ | ✅ |
| konflux |  | ✅ |
... and considering konflux is gonna replace both jenkins and GH actions, we want to be on the safe side, and just add coverage to any konflux PL.
this PR and discussion were spawned from [this comment][1] on the PR which initially added unit-tests to konflux/pull-request PL (#45).
just ensure CI is still ok:
- verify the konflux-pipeline PR check passes, and pipeline-run logs (under the 'run-unit-tests' task) show that test coverage ran
- verify the jenkins job PR …

OCMUI-3696: switch on test-coverage for konflux' "pull-request" PL

---

src/components/clusters/wizards/osd/ClusterSettings/CloudProvider/GcpByocFields/GcpByocFields.tsx
src/components/clusters/wizards/osd/CreateOsdWizard.tsx
src/queries/featureGates/featureConstants.ts

This PR makes fixes to allow WIF as the default auth type for GCP OSD clusters and changes the wording on the WIF tooltip text to fix a couple grammar errors.
Also flips the order for the auth buttons. As Wif is now the first and Service account is the 2nd.
[OCMUI-3604](https://issues.redhat.com/browse/OCMUI-3604) 
[OCMUI-2836](https://issues.redhat.com/browse/OCMUI-2836) 
WIF as the default auth type is behind a feature gate which made this story a bit more tricky. Usually we could just change the formik initialValue for this but because it had to be behind a feature gate I had to edit the initialValues object within the parent component (CreateOSDWizard). 
Because of this, I'm not sure how to add a unit test to properly test this as the logic behind it does not live in the …

OCMUI-3604, OCMUI-2836 - [OSD-GCP] Make WIF auth as the default authentication type, [OSD Wizard] WIF authorization, update Auth Type tooltip

---

src/components/clusters/ClusterDetailsMultiRegion/components/UpgradeSettings/UpgradeSettingsTab.tsx

During the conversion of UpgradeSettingsTab.jsx to tsx, the wrong `UpgradePolicy` type was used instead of `UpgradePolicyWithState` on the schedule variable.  This meant the state of the upgrade was not properly being checked later on in the process.  I corrected the type which fixes the issue.
OCMUI-3712
1. Install a ROSA hosted cluster that is not up-to-date.
`rosa create cluster --cluster-name test-rosa-upgrade --region=us-west-2 --sts --version 4.19.1 --channel-group candidate
`
2. Once cluster is ready, Go cluster's Settings tab.
3. Select the Update strategy as "Recurring updates"
4. Select the day and time values from respective dropdown fields.
5. Click "Save" button.
6. Select the Update strategy as "Individual updates"
7. Click "Save" button.
8. Click "Update" button.
9. In …

OCMUI-3712: Update schedule variable to use proper type so we have access to state of upgrade

---

src/components/common/FormikFormComponents/FormikFieldArray/CompoundFieldArray.jsx
src/components/common/FormikFormComponents/FormikFieldArray/CompoundFieldArray.scss

In the confirm password field in CompoundFieldArray.jsx, when the label "Confirm password *" was wrapping, it caused the input field to drop a line. To fix it I added a no-wrap css property to the field 
Fixes [OCMUI-3618](https://issues.redhat.com/browse/OCMUI-3618)
1. In an existing cluster go to Access control --> htpasswd idp
2. Check the responsiveness of the fields for username, password and confirm password and make sure the fields do not misalign 
|--------------------------------------------------- | --------------------------------------- |
| <img width="565" height="735" alt="ocmui3618_before" src="https://github.com/user-attachments/assets/a1d5f770-1f3f-414b-8a94-d37a3e53b45e" /> …

OCMUI-3618 - When creating a new htpasswd IDP the confirm password field is misaligned

---

src/components/common/PopoverHint.tsx
src/components/common/PopoverHintWithTitle.tsx

Simple PR that removes the extra space between labels and their help icon. Turns out there is a very simple prop  in the Button component built for this sort of thing.
Fixes [OCMUI-3611](https://issues.redhat.com/browse/OCMUI-3611)
1. The easiest place to check the difference in the popover now is in the Cluster settings page of the wizard or in the Accounts and roles page of the rosa wizard 
| <img width="1056" height="734" alt="ocmui3611_before" src="https://github.com/user-attachments/assets/3fe70998-06b6-4199-858c-69e37d08b2bd" /> | <img width="603" height="545" alt="ocmui3611_after" …

OCMUI-3611 - Extra space between form titles and help icon

---

cypress/e2e/osd/OsdCcsWizardValidation.js
cypress/e2e/osd/OsdTrialClusterCreation.js

Update failing test case based on the new definition on GCP authentication
Fixes [OCMUI-3708](https://issues.redhat.com/browse/OCMUI-3708) 
The recent feature revision changes in [OCMUI-3604](https://issues.redhat.com/browse/OCMUI-3604) i.e. regarding the default authentication as "Workload identity feature" in GCP wizard including layout. This breaks e2e tests especially related to various GCP wizard tests. The PR will fix the same.
Run the local server from PR https://github.com/RedHatInsights/uhc-portal/pull/41 i.e. reviewx 41
Run the random test ex:
`yarn cypress run --browser chrome --config baseUrl='https://console.dev.redhat.com/openshift/' --spec cypress/e2e/osd/OsdTrialClusterCreation.js`
Please review and follow the [PR …

[OCMUI-3708]Update failing test case based on the new definition on GCP authentication.

---

src/components/clusters/ClusterDetailsMultiRegion/components/MachinePools/components/EditMachinePoolModal/sections/EditNodeCountSection.test.tsx
src/components/clusters/ClusterDetailsMultiRegion/components/MachinePools/components/EditMachinePoolModal/sections/EditNodeCountSection.tsx

Hide resizing alert during node scaling in ROSA HCP cluster.
Added unit tests for HCP clusters and non HCP clusters.
Fixes [OCMUI-3102](https://issues.redhat.com/browse/OCMUI-3102)
1. Create HCP cluster
2. Go to Details->Machine Pool tab
3. Click on the three dots of the machine pool
4. Choose edit
5. Change Compute node count to 30
6. Make sure the alert doesn't show
|<img width="838" height="736" alt="image" src="https://github.com/user-attachments/assets/b1b6f168-4584-43e0-bfa4-392a1b7be212" /> | <img width="837" height="551" alt="image" …

OCMUI-3102: Hide resizing alert during node scaling in ROSA HCP 

---

src/components/clusters/common/ClusterUpdateLink.jsx

Update ClusterUpdateLink to include cluster readiness check  before rendering update link
Only show link to update cluster version when the cluster is in ready state.  If not, show message stating update is available and direct user to settings tab.
[OCMUI-3711](https://issues.redhat.com/browse/OCMUI-3711)
1. Start installing a new ROSA HCP cluster that is back level on the z stream (so like 4.19.1)
2. While it is installing, check on the Cluster Details -> overview tab under the Version section that there is not a link that opens the upgrade wizard.
3. Once the cluster is done installing and in ready state, there should be an Update link to the Upgrade wizard
| …

OCMUI-3711: Update ClusterUpdateLink to include cluster readiness check

---

src/components/clusters/ClusterDetailsMultiRegion/ClusterDetails.jsx
src/components/clusters/ClusterDetailsMultiRegion/components/AddOns/AddOns.jsx
src/queries/ClusterDetailsQueries/AddOnsTab/useFetchAddOns.ts
src/queries/ClusterDetailsQueries/AddOnsTab/useFetchClusterAddOns.ts

In the HCP clusters there were some API calls made for AddOns which do not exist for HCP clusters.
[OCMUI-3642](https://issues.redhat.com/browse/OCMUI-3642)
1. Open developer console and open network tab. In search type /addon
2. Navigate to ROSA classic cluster and confirm that API calls are being made for AddOns.
3. Empty the network tab and navigate to ROSA HCP cluster and confirm that API calls for AddOns are not being made.
No visual change

OCMUI-3642: fixed redundant api calls for hcp

---

src/common/__tests__/externalAuthHelper.fixtures.ts
src/common/__tests__/restrictTokensHelper.test.ts
src/common/externalAuthHelper.ts
src/common/restrictTokensHelper.ts
src/common/subscriptionCapabilities.ts
src/components/CLILoginPage/CLILoginPage.test.tsx
src/components/clusters/ClusterDetailsMultiRegion/__tests__/ClusterDetails.fixtures.js
src/components/clusters/ClusterDetailsMultiRegion/__tests__/SubscriptionCompliancy.test.jsx
src/components/clusters/ClusterDetailsMultiRegion/components/AccessControl/UsersSection/UsersHelper.ts
src/components/clusters/ClusterDetailsMultiRegion/components/AccessControl/UsersSection/UsersSelector.js
src/components/clusters/ClusterDetailsMultiRegion/components/AccessControl/UsersSection/__tests__/UsersSelectors.test.js
src/components/clusters/ClusterDetailsMultiRegion/components/MachinePools/__tests__/MachinePools.fixtures.js
src/components/clusters/ClusterDetailsMultiRegion/components/MachinePools/__tests__/machinePoolsSelectors.test.ts
src/components/clusters/ClusterDetailsMultiRegion/components/MachinePools/machinePoolsSelectors.ts
src/components/clusters/ClusterTransfer/ClusterTransferList.fixtures.js
src/components/clusters/RegisterCluster/__tests__/registerClusterSelectors.test.ts
src/components/clusters/RegisterCluster/registerClusterSelectors.ts
src/components/clusters/common/EditSubscriptionSettingsDialog/EditSubscriptionSettingsDialog.test.tsx
src/components/clusters/common/HibernateClusterModal/HibernateClusterModalSelectors.js
src/components/clusters/common/Upgrades/UpgradeAcknowledge/__tests__/UpgradeAcknowledgeHelpers.test.ts
src/components/clusters/wizards/common/ClusterSettings/Details/versionSelectHelper.test.ts
src/components/clusters/wizards/common/ClusterSettings/Details/versionSelectHelper.ts
src/components/clusters/wizards/rosa/CreateRosaGetStarted/StepCreateAWSAccountRoles/StepCreateAWSAccountRoles.test.tsx
src/components/clusters/wizards/rosa/ReviewClusterScreen/ReviewClusterScreen.test.jsx
src/components/downloads/DownloadsPage/__tests__/DownloadsPage.test.tsx
src/hooks/__tests__/useCanClusterAutoscale.test.ts
src/hooks/useCanClusterAutoscale.ts

There were lots of places where capabilities were hardcoded as strings creating confusion. This PR replaces them with constant values which all reside in one place for consistency.
[OCMUI-3597](https://issues.redhat.com/browse/OCMUI-3597)
To be fair not sure how to test it. It is a very simple replacement of string values with constant values.
No visualchanges.

OCMUI-3597: replaced hardcoded capabilities with constants

---

src/components/App/App.tsx

Fixing the double scrolling issue re-introduced after HCC migrated to PF6.
Fixes [OCMUI-3653](https://issues.redhat.com/browse/OCMUI-3653)
While waiting for HCC to address this on their side, I realized that we still have an issue in how we calculate our app container height. In theory this fix will make their ticket not necessary anymore.
After the PF6 upgrade the page layout changed, we can't use the viewport height and subtract header and banner size anymore. We also have new content inside the app area (the HCC breadcrumb) and some spacing below the chrome wrapper container (`.chr-render`). I had to change approach and take the size of our container and subtract the breadcrumb size.
Calculating manually the height was and remains a brittle solution. I also explored if we can remove it …

OCMUI-3653 Double scrolling issue 

---

src/queries/featureGates/featureConstants.ts

A new feature gate was created in both production and staging.  This PR just adds that feature gate into the featureConstants file so it is available when coding begins.
This PR does nothing but add an unused variable.
Fixes [OCMUI-3684](https://issues.redhat.com/browse/OCMUI-3684) 
None
Nothing to test 

OCMUI-3684 Add new feature gate

---

src/components/clusters/wizards/rosa/AccountsRolesScreen/AccountsRolesScreen.tsx

Billing is currently not working in FedRAMP HCP. to allow QE to start testing bypass was implemented on the backend and this PR addresses that issue on the UI side.
[OCMUI-3748](https://issues.redhat.com/browse/OCMUI-3748)
|  |  |

OCMUI-3748: bypass fedramp billing

---

src/components/clusters/common/Upgrades/UpgradeWizard/FinishedStep.tsx

Simple replacement of DataFormat on final step upgrade wizard to PF6 DateFormat
[OCMUI-3789](https://issues.redhat.com/browse/OCMUI-3789)
Create cluster with older version.
Try to manually schedule an upgrade further in the future time.
When upgrade is scheduled you will be presented with confirmation modal where this component is rendered.
|  | <img width="1916" height="1100" alt="image" src="https://github.com/user-attachments/assets/3259fd0d-5005-4593-9260-ed659af03323" />|
Please review and follow the [PR process](https://github.com/RedHatInsights/uhc-portal/blob/main/docs/pull-request-process …

OCMUI-3789: replaced DataFormat on final step upgrade wizard

---

src/components/clusters/wizards/common/NetworkingSection/AvailabilityZoneSelection.jsx

Fix ability to select AZ when vpc changes.
User cannot select an Availability Zone value from the dropdown after changing the VPC in the "Virtual Private Cloud (VPC) Subnet Settings" step.
Fixes [OCMUI-3750](https://issues.redhat.com/browse/OCMUI-3750) -->
0. Create a couple of VPCs in an aws region of your choice. 
1. Open the ROSA wizard.
2. Select the control plane type "Classic architecture."
4. Fill in all required fields in each step
5. Click "Install into existing VPC" and go to Networking > VPC Settings.
6. Select a VPC from the dropdown.
7. Select a different VPC from the dropdown.
8. Try to select a value from the Availability Zone dropdown.
9. You should be able to select an AZ and it actual be selected.
Please review and follow the [PR …

OCMUI-3750: Fix ability to select AZ when vpc changes

---

src/components/clusters/ClusterDetailsMultiRegion/components/Networking/components/ApplicationIngressCard/ApplicationIngressCard.tsx
src/components/common/ReduxFormComponents_deprecated/ReduxCheckbox.jsx

When setting or editing the switches for: 
- Namespace ownership policy
- Wildcard policy
- Load balance type
The value next to the switch did not change which makes it confusing what the actual values is.
Fixes [OCMUI-3731](https://issues.redhat.com/browse/OCMUI-3731) 
Areas where you can edit the value (wizards, Edit application ingress) there as a "labelOff" attribute that is sent down to a PatternFly Switch prop.  In PF 6 this prop was removed.  This PR fixes to switch the label based on the switch state.
Secondly on Cluster details > Networking tab > Application ingress, it appears that the state of these switches always had static labels (aka they never had a "labelOff" value).  This PR fixes that. 
- Build an OSD AWS cluster (or use: kim-osd-aws-9-19-2).  
- Go to the Networking …

OCMUI-3731 Fix networking switches

---

src/components/clusters/ClusterDetailsMultiRegion/components/ClusterDetailsTop/ClusterDetailsTop.jsx

for archived OCP clusters, the count variable hasSubscriptionCompliancyAlert was incorrectly set to true due to an || vs && operator blunder for the variable. This was causing the alerts expandable section to be showing with a value of 1, without having an actual alert in it. 
Fixes [OCMUI-3826](https://issues.redhat.com/browse/OCMUI-3826) 
1. From the cluster list, go to the cluster archives and access any OCP cluster
2. The alerts and notifications expandable section should not be showing 
| <img width="1603" height="684" alt="ocmui3826_before" …

OCMUI-3826 - Misleading "Alert and recommendations" banner for archived /Deleted OCP clusters

---

src/components/clusters/ClusterDetailsMultiRegion/components/MachinePools/MachinePoolsTable.jsx
src/components/clusters/ClusterDetailsMultiRegion/components/MachinePools/UpdateMachinePools/UpdateMachinePoolModal.tsx

Action resolver was updated a little bit ago to change the function parameters to only accept a machinePool object.  However, the click action onClickUpdateAction still had the old parameters.  I updated the parameters and now we are sending the machinePool object properly to the modal window.
The machine pool and machine pool table files are jsx while the update files and helper files are typescript.  I would guess we would not have had this issue if we had strong typed the functions.  
Fixes [OCMUI-3663](https://issues.redhat.com/browse/OCMUI-3663) 
I did not try to convert the machine pool files to typescript as this is a critical bug that needs to be fix ASAP.  We do have a backlog item to convert these files in the future and hopefully silly bugs like this will be prevented.
1. …

OCMUI-3663: Fix crash on Machine pool update
